# Generated by Django 3.2.4 on 2021-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ManyToManyField(to='newsapp.Comment'),
        ),
    ]
