# Generated by Django 3.2.4 on 2021-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_news_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_img', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('title', models.CharField(default='', max_length=255)),
                ('comments', models.ManyToManyField(to='newsapp.Comment')),
            ],
        ),
    ]
